config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :jobs
  resources :charges
  root 'jobs#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :jobs
end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :category
  belongs_to :user

  validates :category , presence: :true
  validates :title, presence: :true
  validates :description, presence: :true
  validates :company, presence: :true
  validates :url, presence: :true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :jobs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
  end

  def create
    # Amount in cents
    @amount = 1000

    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Rails Stripe customer',
      :currency    => 'usd'
    )

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  before_action :find_job, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]

  def index
    if params[:category].blank?
      @jobs=Job.all.order("created_at DESC")
    else
      @category_id = Category.find_by(name: params[:category]).id
      @jobs= Job.where(category_id: @category_id).order("created_at DESC")
    end
  end

  def show
  end

  def new
    @job=Job.new
  end

  def create
    @job=current_user.jobs.build(jobs_params)
    if @job.save
      redirect_to @job
      flash[:notice] = "Job Created Successfully"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @job.update(jobs_params)
     redirect_to @job
     flash[:notice] = "Job Updated Successfully"
    else
     render 'edit'
    end
  end

  def destroy
    @job.destroy
    redirect_to root_path
  end

  private

    def jobs_params
      params.require(:job).permit(:title, :description, :company, :url, :category_id)
    end

    def find_job
      @job=Job.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/jobs_helper.rb
module JobsHelper

  def correct_user?(user)
    current_user == user
  end

end

app/views/charges/create.html.haml
%h1{:style => "text-align:center;"}
  Thanks you paid
  %strong $10.00!

app/views/charges/new.html.haml
%h1{:style => "text-align:center;"}
  Please click on Pay with Card to pay
  %strong $10.00!

  = form_tag charges_path do
    %article
      - if flash[:error].present?
        #error_explanation
          %p= flash[:error]
    %script.stripe-button{"data-amount" => "1000", "data-description" => "A month's subscription", "data-key" => "#{Rails.configuration.stripe[:publishable_key]}", "data-locale" => "auto", :src => "https://checkout.stripe.com/checkout.js"}

app/views/jobs/_form.html.haml
=simple_form_for(@job, html:{class: 'form-horizontal'}) do |f|
  -if @job.errors.any?
    #error_explanation
      %h2= pluralize(@job.errors.count, "error")
      prohibited this todo_list from being saved
      %ul
        -@job.errors.full_messages.each do |message|
          %li= message
  .form
    =f.collection_select :category_id, Category.all, :id, :name, {prompt: "Choose A Category"}, input_html: {class: "dropdown-toggle"}
  =f.input :title, label:'Job Title', input_html: {class: "form-control"}
  =f.input :description, label:'Job Description', input_html: {class: "form-control"}
  =f.input :company, label:'Company', input_html: {class: "form-control"}
  =f.input :url, label:'Job URL', input_html: {class: "form-control"}
  %br/
  .form
    =f.button :submit,class: "btn btn-sm btn-default"
    =link_to "Back",root_path,class: "btn btn-sm btn-default"

app/views/jobs/edit.html.haml
.form
  %h1 Edit Job
=render 'form'

app/views/jobs/index.html.haml
#jobs
  -@jobs.each do |job|
    .job
      %h2= link_to job.title,job
      %p= truncate(job.description, length:80)

app/views/jobs/new.html.haml
.form
  %h1 New Job
=render 'form'

app/views/jobs/show.html.haml
#jobs
  .job
    %h2=@job.title
    %p= @job.description
    %p= @job.company
    %button.btn.btn-lg.btn-default=link_to "Apply For Job",@job.url
#links
  =link_to "Back",root_path, class: 'btn btn-sm btn-default'
  -if correct_user?(@job.user)
    =link_to "Edit",edit_job_path, class: 'btn btn-sm btn-default'
    =link_to "Delete",job_path(@job), method: :delete, data: {confirm: "Are You Sure?"}, class: 'btn btn-sm btn-default'
%hr{:style => "opacity: 0.6;"}

app/views/layouts/application.html.haml
!!!5
%html
%head
  %title Smart Jobs
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags
%body
  %nav.navbar.navbar-default
    .container
      .navbar-brand Smart Jobs
      %ul.nav.navbar-nav
        %li=link_to "All Jobs",root_path
        -Category.all.each do|category|
          %li= link_to category.name,jobs_path(category: category.name)
      -if user_signed_in?
        =link_to "Log Out", destroy_user_session_path , class: "navbar-text navbar-right navbar-link",method: :delete
        =link_to "New Job", new_job_path, class: "navbar-text navbar-right navbar-link"
      -else
        =link_to "Sign Up", new_user_registration_path , class: "navbar-text navbar-right navbar-link"
        =link_to "Sign In", user_session_path , class: "navbar-text navbar-right navbar-link"
      =link_to "Pricing", new_charge_path , class: "navbar-text navbar-right navbar-link"
  .container
    #margin
      .col-md-8.col-md-offset-1
        -flash.each do |name,msg|
          =content_tag(:div, msg , class: "notice")
        = yield

app/views/layouts/charges.html.haml
!!!5
%html
  %head
  %body
    = yield